import json
import re
import time
from typing import Callable, Optional

from groq import Groq

from benchmarks import BENCHMARKS
from scoring import calculate_overall_score, normalise_dimension_scores

MODEL = "openai/gpt-oss-20b"
# Backwards-compatible export used by app.py
MODEL_DEFAULT = MODEL
# Keep the combined request footprint below the user's 8K TPM on-demand ceiling.
MAX_SOURCE_CHARS = 3_500
MAX_OBJECTIVE_CHARS = 1_800
MAX_CONTEXT_CHARS = 3_000
RETRY_DELAYS = (2.0, 5.0)

# Fixed boilerplate is written locally instead of being generated by the model:
# it never varies, it costs output tokens, and a missing field used to abort the run.
DISCLAIMER = (
    "This is an AI-generated modernisation proposal prepared for teacher and departmental "
    "review. It is not an approved curriculum and must be validated against university "
    "regulations, accreditation requirements and available resources before adoption."
)


# ---------------------------------------------------------------- json helpers

def _clean_json(text: str) -> dict:
    text = (text or "").strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
    text = re.sub(r"\s*```$", "", text)
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start >= 0 and end > start:
            value = json.loads(text[start:end + 1])
        else:
            raise
    return value if isinstance(value, dict) else {"value": value}


# Keys whose value speaks for itself and needs no "Key: " prefix when flattened.
_BARE_KEYS = {
    "title", "change", "course", "course_or_area", "name", "gap", "action",
    "text", "value", "summary", "description", "item",
}


def flatten_text(value) -> str:
    """Render any payload fragment as readable prose - never raw JSON.

    A model sometimes returns an object where the schema asked for a string.
    Dumping that as JSON leaks braces and quotes into the UI and the PDF, so it
    is flattened into a sentence instead. JSON that arrives already wrapped in a
    string is parsed first, then flattened the same way.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        stripped = value.strip()
        if stripped[:1] in ("{", "["):
            try:
                return flatten_text(json.loads(stripped))
            except Exception:
                return value
        return value
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "; ".join(part for part in (flatten_text(v) for v in value) if part)
    if isinstance(value, dict):
        parts = []
        for key, item in value.items():
            text = flatten_text(item)
            if not text:
                continue
            parts.append(text if key in _BARE_KEYS else f"{str(key).replace('_', ' ').capitalize()}: {text}")
        return " - ".join(parts)
    return str(value)


def _default_for(schema: dict):
    kind = schema.get("type")
    if kind == "string":
        enum = schema.get("enum")
        # Enums are ordered most-urgent first, so fall back to the least urgent
        # value rather than overstating a priority the model never gave.
        return enum[-1] if enum else ""
    if kind == "integer":
        return int(schema.get("minimum", 0))
    if kind == "number":
        return float(schema.get("minimum", 0))
    if kind == "boolean":
        return False
    if kind == "array":
        return []
    if kind == "object":
        return _coerce({}, schema)
    return ""


def _coerce(value, schema: dict):
    """Shape a parsed payload to the schema, filling any missing required field.

    The model occasionally omits a required key. Rather than losing the whole
    analysis, the missing key is filled with a safe empty value and the run
    continues; every consumer already reads these fields defensively.
    """
    kind = schema.get("type")
    if kind == "object":
        source = value if isinstance(value, dict) else {}
        props = schema.get("properties", {})
        required = schema.get("required", [])
        out = {}
        for key, sub in props.items():
            if key in source and source[key] is not None:
                out[key] = _coerce(source[key], sub)
            elif key in required:
                out[key] = _default_for(sub)
        return out
    if kind == "array":
        if not isinstance(value, list):
            return []
        items = schema.get("items", {})
        out = [_coerce(v, items) for v in value]
        limit = schema.get("maxItems")
        return out[:limit] if limit else out
    if kind == "integer":
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return int(schema.get("minimum", 0))
    if kind == "number":
        try:
            return float(value)
        except (TypeError, ValueError):
            return float(schema.get("minimum", 0))
    if kind == "string":
        return flatten_text(value)
    return value


def _failed_generation(exc: Exception) -> Optional[str]:
    """Recover the model text Groq rejected during schema validation."""
    body = getattr(exc, "body", None)
    if isinstance(body, dict):
        error = body.get("error")
        if isinstance(error, dict) and error.get("failed_generation"):
            return error["failed_generation"]
    text = str(exc)
    match = re.search(r"'failed_generation':\s*(['\"])(.*?)\1\s*\}", text, re.S)
    if match:
        return match.group(2).encode().decode("unicode_escape", "ignore")
    return None


def _trim(text: str, limit: int) -> str:
    text = text or ""
    if len(text) <= limit:
        return text
    head = int(limit * 0.68)
    tail = limit - head
    return text[:head] + "\n[...middle omitted...]\n" + text[-tail:]


def _compact(value, max_chars: int = MAX_CONTEXT_CHARS):
    text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    if len(text) <= max_chars:
        return value
    return {"truncated_context": text[:max_chars]}


# ------------------------------------------------------------------ model call

def _chat(client: Groq, messages: list[dict], *, max_tokens: int, schema: dict) -> dict:
    """Call the model and always return a dict shaped like ``schema``."""
    last_err: Optional[Exception] = None
    payload = list(messages)

    for attempt, delay in enumerate((0.0, *RETRY_DELAYS)):
        if delay:
            time.sleep(delay)
        try:
            response = client.chat.completions.create(
                model=MODEL,
                messages=payload,
                temperature=0.0,
                reasoning_effort="low",
                max_completion_tokens=max_tokens,
                response_format={
                    "type": "json_schema",
                    "json_schema": {
                        "name": schema["name"],
                        "strict": True,
                        "schema": schema["schema"],
                    },
                },
            )
            content = response.choices[0].message.content
            return _coerce(_clean_json(content), schema["schema"])
        except Exception as exc:
            last_err = exc
            text = str(exc)

            # Schema validation rejected by Groq: the text is usually complete and
            # useful, only a field is missing. Salvage it instead of failing.
            if "json_validate_failed" in text or "does not match the expected schema" in text:
                salvaged = _failed_generation(exc)
                if salvaged:
                    try:
                        return _coerce(_clean_json(salvaged), schema["schema"])
                    except Exception:
                        pass
                required = ", ".join(schema["schema"].get("required", []))
                payload = list(messages) + [{
                    "role": "system",
                    "content": (
                        "The previous reply was rejected. Return ONE JSON object that "
                        f"includes every required key: {required}. Keep every value short."
                    ),
                }]
                continue

            # Output ran out of room and the JSON is truncated: retry, asking for less.
            if isinstance(exc, json.JSONDecodeError):
                payload = list(messages) + [{
                    "role": "system",
                    "content": "Reply with complete, valid JSON only. Keep every value under 25 words.",
                }]
                continue

            if "429" in text or "rate_limit_exceeded" in text:
                continue

            raise

    # Every attempt failed: degrade to an empty, correctly shaped result so the
    # rest of the report still renders.
    if attempt and last_err is not None and (
        "json_validate_failed" in str(last_err) or isinstance(last_err, json.JSONDecodeError)
    ):
        return _coerce({}, schema["schema"])
    raise last_err


# --------------------------------------------------------------------- schemas

SCHEMA_STRUCTURE = {
    "name": "curriculum_structure",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "program_summary": {"type": "string"},
            "course_inventory": {"type": "array", "items": {"type": "string"}},
            "learning_outcomes": {"type": "array", "items": {"type": "string"}},
            "tools_and_technologies": {"type": "array", "items": {"type": "string"}},
            "assessment_signals": {"type": "array", "items": {"type": "string"}},
        },
        "required": ["program_summary", "course_inventory", "learning_outcomes", "tools_and_technologies", "assessment_signals"],
    },
}

SCHEMA_BENCHMARK = {
    "name": "curriculum_benchmark",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "dimension_scores": {
                "type": "array", "maxItems": 8,
                "items": {
                    "type": "object", "additionalProperties": False,
                    "properties": {
                        "id": {"type": "string"},
                        "score": {"type": "integer", "minimum": 0, "maximum": 100},
                        "evidence": {"type": "string"},
                        "missing": {"type": "string"},
                        "priority": {"type": "string", "enum": ["Immediate", "Mandatory", "Optional"]},
                    },
                    "required": ["id", "score", "evidence", "missing", "priority"],
                },
            },
            "top_global_gaps": {"type": "array", "items": {"type": "string"}, "maxItems": 4},
            "first_gap_point": {"type": "string"},
            "benchmark_note": {"type": "string"},
        },
        "required": ["dimension_scores", "top_global_gaps", "first_gap_point", "benchmark_note"],
    },
}

SCHEMA_PLAN = {
    "name": "modernisation_plan",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "first_gap": {"type": "string"},
            "critical_gaps": {"type": "array", "items": {"type": "string"}, "maxItems": 4},
            "recommendations": {
                "type": "array", "maxItems": 5,
                "items": {
                    "type": "object", "additionalProperties": False,
                    "properties": {
                        "title": {"type": "string"},
                        "priority": {"type": "string", "enum": ["Immediate", "Mandatory", "Optional"]},
                        "action": {"type": "string"},
                    },
                    "required": ["title", "priority", "action"],
                },
            },
            "proposed_course_updates": {"type": "array", "items": {"type": "string"}},
            "teacher_message": {"type": "string"},
        },
        "required": ["first_gap", "critical_gaps", "recommendations", "proposed_course_updates", "teacher_message"],
    },
}

# NOTE: 'disclaimer' is deliberately NOT part of this schema. It is fixed text
# added locally after the call, which removes the required field the model kept
# dropping and saves output tokens on every analysis.
SCHEMA_DRAFT = {
    "name": "curriculum_draft",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "executive_summary": {"type": "string"},
            "principles": {"type": "array", "items": {"type": "string"}, "maxItems": 4},
            "revised_curriculum": {
                "type": "array", "maxItems": 5,
                "items": {
                    "type": "object", "additionalProperties": False,
                    "properties": {
                        "course_or_area": {"type": "string"},
                        "status": {"type": "string"},
                        "updated_scope": {"type": "string"},
                        "key_topics": {"type": "string"},
                        "practical_work": {"type": "string"},
                        "assessment": {"type": "string"},
                    },
                    "required": ["course_or_area", "status", "updated_scope", "key_topics", "practical_work", "assessment"],
                },
            },
            "change_log": {
                "type": "array", "maxItems": 5,
                "items": {
                    "type": "object", "additionalProperties": False,
                    "properties": {
                        "change": {"type": "string"},
                        "old_state": {"type": "string"},
                        "new_state": {"type": "string"},
                        "reason": {"type": "string"},
                    },
                    "required": ["change", "old_state", "new_state", "reason"],
                },
            },
            "teacher_review_points": {"type": "array", "items": {"type": "string"}, "maxItems": 4},
        },
        "required": ["executive_summary", "principles", "revised_curriculum", "change_log", "teacher_review_points"],
    },
}


def _local_extract(curriculum_text: str, objectives_text: str) -> dict:
    curriculum = _trim(curriculum_text, MAX_SOURCE_CHARS)
    objectives = _trim(objectives_text, MAX_OBJECTIVE_CHARS)
    return {
        "source_excerpt": curriculum,
        "objectives_excerpt": objectives,
    }


# -------------------------------------------------------------------- workflow

def run_workflow(
    api_key: str,
    university: str,
    subject: str,
    curriculum_text: str,
    learning_objectives_text: str,
    progress: Optional[Callable[[int, str], None]] = None,
) -> dict:
    client = Groq(api_key=api_key)

    def update(p: int, msg: str):
        if progress:
            progress(p, msg)

    source = _local_extract(curriculum_text, learning_objectives_text)

    update(15, "Reading and structuring the submitted curriculum")
    structure_prompt = f"""
Analyse the submitted curriculum for the subject '{subject}' at '{university}'. Use only the supplied text. Be concise.
Return only the required structured fields. Preserve ALL distinct course topics, outcomes, tools and assessment signals found in the supplied documents; do not truncate or summarise lists to a fixed maximum. Do not invent content.

CURRICULUM:\n{source['source_excerpt']}

LEARNING OBJECTIVES:\n{source['objectives_excerpt']}
"""
    structure = _chat(
        client,
        [{"role": "system", "content": "Extract factual curriculum information. Reply with one JSON object containing every required key."}, {"role": "user", "content": structure_prompt}],
        max_tokens=500,
        schema=SCHEMA_STRUCTURE,
    )

    update(40, "Comparing the curriculum with modern global benchmarks")
    benchmark_text = "\n".join(f"{b['id']}: {b['name']} - {b['signals']}" for b in BENCHMARKS[:8])
    benchmark_prompt = f"""
Benchmark this {subject} curriculum against current global and industry-facing expectations. Do not claim a single vendor is mandatory. Score each listed dimension 0-100 using evidence from the structured curriculum; be concise.

DIMENSIONS:\n{benchmark_text}

STRUCTURED CURRICULUM:\n{json.dumps(_compact(structure), ensure_ascii=False)}
"""
    comparison = _chat(
        client,
        [{"role": "system", "content": "Return a compact benchmark assessment. Reply with one JSON object containing every required key."}, {"role": "user", "content": benchmark_prompt}],
        max_tokens=650,
        schema=SCHEMA_BENCHMARK,
    )
    dims = normalise_dimension_scores(comparison.get("dimension_scores", []))
    overall = calculate_overall_score(dims)

    update(65, "Identifying the most important gaps and practical improvements")
    plan_prompt = f"""
Create a concise modernisation plan for {university}'s {subject}. Preserve valid foundations. Focus on the most important missing content, tools, practical work and assessment changes. Use Immediate, Mandatory and Optional priorities.

SCORE: {overall}/100
BENCHMARK:\n{json.dumps(_compact(comparison), ensure_ascii=False)}
STRUCTURE:\n{json.dumps(_compact(structure), ensure_ascii=False)}
"""
    plan = _chat(
        client,
        [{"role": "system", "content": "Design practical curriculum improvements. Reply with one JSON object containing every required key."}, {"role": "user", "content": plan_prompt}],
        max_tokens=750,
        schema=SCHEMA_PLAN,
    )

    update(88, "Preparing the proposed modernised curriculum")
    draft_prompt = f"""
Prepare a concise teacher-reviewable modernised curriculum proposal for {university}'s {subject}. This is a proposal, not an approved curriculum. Keep entries short enough for a 4-page report: at most 5 curriculum rows, at most 5 change-log entries, and no value longer than 40 words. Prefer high-value changes over detail. Do not add a disclaimer; one is added automatically.

SCORE: {overall}/100
PLAN:\n{json.dumps(_compact(plan), ensure_ascii=False)}
BENCHMARK:\n{json.dumps(_compact(comparison), ensure_ascii=False)}
"""
    draft = _chat(
        client,
        [{"role": "system", "content": "Draft a concise modern curriculum proposal. Reply with one JSON object containing every required key."}, {"role": "user", "content": draft_prompt}],
        max_tokens=900,
        schema=SCHEMA_DRAFT,
    )
    draft["disclaimer"] = DISCLAIMER

    update(100, "Analysis complete")
    return {
        "university": university,
        "subject": subject,
        "score": overall,
        "band": "HIGH WARNING" if overall < 50 else "IMPROVEMENT REQUIRED" if overall <= 80 else "FUTURE-READY",
        "structure": structure,
        "benchmark": {
            "dimension_scores": dims,
            "top_global_gaps": comparison.get("top_global_gaps", []),
            "first_gap_point": comparison.get("first_gap_point", ""),
            "benchmark_note": comparison.get("benchmark_note", ""),
        },
        "gaps": {
            "first_gap": plan.get("first_gap", comparison.get("first_gap_point", "")),
            "critical_gaps": plan.get("critical_gaps", []),
            "teacher_message": plan.get("teacher_message", ""),
        },
        "recommendations": {
            "recommendations": plan.get("recommendations", []),
            "proposed_course_updates": plan.get("proposed_course_updates", []),
        },
        "draft": draft,
    }
